# Generated by Django 4.1 on 2022-09-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_mywatchlistitem_delete_watchlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='watched',
            field=models.BooleanField(),
        ),
    ]
